# Django configuration for EAA donation portal
#
# ***** DO NOT EDIT THIS FILE *****
#
# This file is managed by Salt via salt://eaa/web/templates/django-settings.jinja

import os
import datetime
from settings import BASE_DIR

#############################
### General Configuration ###
#############################

# Debug mode (do *not* use in production)
DEBUG = True

# Directory where various secrets are stored (e.g. RSA keys)
SECRETS_DIR = os.path.join(BASE_DIR, 'secrets')

# Directory where static files are collected and served from
STATIC_ROOT = os.path.join(BASE_DIR, 'tmp/static')


#######################
### Django Security ###
#######################

# Secret key used to provide cryptographic signing
SECRET_KEY = 'development'


############################
### Database Connections ###
############################

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'eaa',
        'USER': 'dev',
        'PASSWORD': '',
        'HOST': '',
        'PORT': '',
    }
}


##############
### Celery ###
##############

BROKER_URL = 'redis://localhost:6379'


#############
### Redis ###
#############

REDIS_HOST = 'localhost'
REDIS_PORT = '6379'


################
### Postmark ###
################

EMAIL_BACKEND = 'postmark.django_backend.EmailBackend'
POSTMARK_API_KEY = 'secret'
POSTMARK_SENDER = 'donations@eaa.org.au'
POSTMARK_TEST_MODE = True
POSTMARK_TRACK_OPENS = False


############
### Xero ###
############

XERO_RSA_KEY = 'secret'
XERO_CONSUMER_KEY = 'secret'
XERO_INCOMING_ACCOUNT_ID = u'secret'
XERO_DAYS_TO_IMPORT = 300


##############
### Sentry ###
##############

# Enable Raven for reporting errors to Sentry
ENABLE_SENTRY = False

# vim: syntax=python cc=80 tw=79 ts=4 sw=4 sts=4 et sr
