# This can be useful for local development where you want to run Django on your
# local machine with supporting services like PostgreSQL and Redis in docker 
# containers.

services:
  db:
    image: postgres:17.5
    environment:
      POSTGRES_DB: donations
      POSTGRES_USER: eaa
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8.0.1
    ports:
      - "6379:6379"

volumes:
  postgres_data: