# This can be useful for local development where you want to run Django on your
# local machine with supporting services like PostgreSQL and Redis in Docker 
# containers. Useful for things like automated testing which requires a display
# server, or running locally installed apps like Claude Code.

services:
  db:
    image: postgres:17.5
    environment:
      POSTGRES_DB: donations
      POSTGRES_USER: eaa
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8.0.1
    ports:
      - "6379:6379"

  memcached:
    image: memcached:1.6.38
    ports:
      - "11211:11211"

volumes:
  postgres_data: