import json

from django.core.management.base import BaseCommand

from donation.models import PartnerCharity, ReferralSource


def dump_partner_charities():
    json_strs = []
    for charity in PartnerCharity.objects.filter(active=True).order_by('order').values('slug_id', 'name'):
        json_strs.append(json.dumps(charity))
    return 'export const charities = [%s]' % ', '.join(json_strs)


def dump_referral_sources():
    json_strs = []
    for slug, reason in ReferralSource.objects.filter(enabled=True).order_by('order').values_list('slug_id', 'reason'):
        json_strs.append(json.dumps({'value': slug, 'label': reason}))
    return 'export const referralSources = [%s]' % ', '.join(json_strs)


class Command(BaseCommand):
    args = "filename"
    help = "Dumps charity and referral sourcce data in javascript format (not JSON) to the given file."

    def add_arguments(self, parser):
        parser.add_argument('filename')

    def handle(self, *args, **options):
        filename = options['filename']
        functions = [dump_partner_charities, dump_referral_sources]
        data = "// Generated by `manage.py dump_react_form_data`\n" + "\n".join([f() for f in functions])
        with open(filename, 'w') as outfile:
            outfile.write(data)
